#+TITLE: Frequently asked questions

* I want to use a non-departmental computer. What should I do?

First, if you have a departmental computer, you should use it because it is already configured for this course.

If that is not the case, you need to install the following programs.

1. Python https://www.continuum.io/downloads (Windows, Mac and Linux)
2. LaTeX  https://www.tug.org/texlive/doc.html (Windows, Linux) ([[https://www.tug.org/mactex/][Mac]])
3. git    [[http://git-scm.com/download/win][Windows]] [[http://git-scm.com/download/mac][Mac]] [[http://git-scm.com/download/linux][Linux]]

You also must make sure you have OpenSSH installed. This comes with git on Windows.

After those are installed, you need to install scimax. Go to http://github.com/jkitchin/scimax and follow the installation directions.

I recommend you do this on your Desktop.

* I do not want to use Emacs, can I use something else?
Everything we will do is built into Emacs. There is nothing else that will do what we need. If you like Vim, you should look into configuring Emacs to act like Vim (http://www.emacswiki.org/emacs/ViperMode).

While it is technically possible to do everything via command-line utilities, I will not spend the time explaining how to do that. It is already coded into Emacs.

* I do not like Python, can I use Matlab? or some other software package?

We will not consider any other math software tools in this class besides Python, and some things we will do are not yet possible with Matlab or other tools.

You may use Matlab  if you choose, under the following conditions:

1. All of the m-files you create for each assignment must be located in the assignment directory. These will automatically be uploaded to the server for grading.

2. You must publish your m-file to a pdf in Matlab, and you must put a link to the pdf in your assignment org-file so we know where it is. We will not look for the file, the link must be there, and it must open the pdf.

3. We will not provide help in troubleshooting Matlab or other software problems. There is a Math Software TA (Pablo Garcia-Herreros, pgarciah@andrew.cmu.edu) who may be able to help you with those issues.

We will provide complete support for solving problems with Python.

* I see gray boxes for equations.

Make sure LaTeX is installed.

If you run Windows, try this in your init.el file:

(setq temporary-file-directory (expand-file-name "~/../Local/Temp"))


* I typed my email password into Emacs incorrectly and now I cannot send mail
Emacs remembers your password for convenience. Unfortunately it remembers bad ones too. Click on this link to make it forget, and send your mail again.

elisp:auth-source-forget-all-cached

